### PR TITLE
LPS-54562

### PR DESCRIPTION
**Pull request by jcampoy**
Hi Michael, I've tested this issue and the fix solves the problem, however, could you take a look? May be this change could break other seachs but I think this is the old configuration we have in others versions of the plugins in where this works fine.

Thank you in advance.

Jose

### CODE REVIEW

**Comment by mhan810** [comment]
Hey Jose can you send to @arboliviera?  He's refactoring solr4 rt now.



*From:* Jose A. Jiménez [mailto:notifications@github.com]
*Sent:* Thursday, March 26, 2015 10:40 AM
*To:* mhan810/liferay-plugins
*Subject:* [liferay-plugins] LPS-54562 (#55)



Hi Michael, I've tested this issue and the fix solves the problem, however,
could you take a look? May be this change could break other seachs but I
think this is the old configuration we have in others versions of the
plugins in where this works fine.

Thank you in advance.

Jose
------------------------------
You can view, comment on, or merge this pull request online at:

  https://github.com/mhan810/liferay-plugins/pull/55
Commit Summary

   - LPS-54458 Fix test-cache-configuration-portlet
   - LPS-54478 removing plugins see portal-sso-token
   - LPS-51081 Support for variable number of arguments in gradle-execute
   - LPS-51081 Error messages
   - LPS-51081 Consistency
   - LPS-51081 Redirect Ant calls to Gradle
   - LPS-51081 In case of error, Gradle should not say "Build successful"
   - LPS-51081 Better way to read properties
   - LPS-51081 SF
   - SYNC-1308 Files in trash should not be downloadable
   - LPS-54506
   - Sort
   - LPS-51081 Gradle "format-source" task
   - LPS-51081 Create web
   - LPS-51081 Create ext
   - LPS-51081 Add app.servers.gradle
   - LPS-51081 SF
   - LPS-51081 Sort
   - LPS-51081 rename
   - LPS-51081 Remove task inputs and outputs declaration so to not have a
   "cleanFormatSource" task
   - LPS-51081 Create hook
   - LPS-54511 Fix ivy.xml template for hooks
   - LPS-54508 Add search API that allows start and end input
   - LPS-51081 Create portlet
   - LPS-51081 "compile" is just a shortcut for "compileJava", use
   "classes" to execute custom tasks before "war"
   - LPS-54562 Dynamic config for other fields sould be indexed as string
   - LPS-54562 Write the final queryString in the logs and change to debug
   the log level of debugging information

File Changes

   - *A* app-servers.gradle
   <https://github.com/mhan810/liferay-plugins/pull/55/files#diff-0> (109)
   - *M* build-common.xml
   <https://github.com/mhan810/liferay-plugins/pull/55/files#diff-1> (56)
   - *M* build-plugins.gradle
   <https://github.com/mhan810/liferay-plugins/pull/55/files#diff-2> (30)
   - *M* build-themes.gradle
   <https://github.com/mhan810/liferay-plugins/pull/55/files#diff-3> (2)
   - *M* build.gradle
   <https://github.com/mhan810/liferay-plugins/pull/55/files#diff-4> (1)
   - *M* dependencies/com.liferay.ant.bnd/ivy.xml
   <https://github.com/mhan810/liferay-plugins/pull/55/files#diff-5> (2)
   - *M* dependencies/com.liferay.ant.bnd/ivy.xml.MD5
   <https://github.com/mhan810/liferay-plugins/pull/55/files#diff-6> (2)
   - *M* dependencies/com.liferay.ant.bnd/lib/com.liferay.ant.bnd.jar
   <https://github.com/mhan810/liferay-plugins/pull/55/files#diff-7> (0)
   - *M* ext/build.xml
   <https://github.com/mhan810/liferay-plugins/pull/55/files#diff-8> (46)
   - *M* ext/create.bat
   <https://github.com/mhan810/liferay-plugins/pull/55/files#diff-9> (2)
   - *M* ext/create.sh
   <https://github.com/mhan810/liferay-plugins/pull/55/files#diff-10> (4)
   - *M* gradle.properties
   <https://github.com/mhan810/liferay-plugins/pull/55/files#diff-11> (4)
   - *M* hooks/build.xml
   <https://github.com/mhan810/liferay-plugins/pull/55/files#diff-12> (44)
   - *M* hooks/create.bat
   <https://github.com/mhan810/liferay-plugins/pull/55/files#diff-13> (2)
   - *M* hooks/create.sh
   <https://github.com/mhan810/liferay-plugins/pull/55/files#diff-14> (4)
   - *D* hooks/shibboleth-hook/.classpath
   <https://github.com/mhan810/liferay-plugins/pull/55/files#diff-15> (21)
   - *D* hooks/shibboleth-hook/.project
   <https://github.com/mhan810/liferay-plugins/pull/55/files#diff-16> (16)
   - *D* hooks/shibboleth-hook/build.gradle
   <https://github.com/mhan810/liferay-plugins/pull/55/files#diff-17> (0)
   - *D* hooks/shibboleth-hook/build.xml
   <https://github.com/mhan810/liferay-plugins/pull/55/files#diff-18> (6)
   - *D*
   hooks/shibboleth-hook/docroot/META-INF/custom_jsps/html/portlet/portal_settings/authentication/shibboleth.jsp
   <https://github.com/mhan810/liferay-plugins/pull/55/files#diff-19> (52)
   - *D* hooks/shibboleth-hook/docroot/WEB-INF/lib/.gitignore
   <https://github.com/mhan810/liferay-plugins/pull/55/files#diff-20> (5)
   - *D* hooks/shibboleth-hook/docroot/WEB-INF/liferay-hook.xml
   <https://github.com/mhan810/liferay-plugins/pull/55/files#diff-21> (8)
   - *D*
   hooks/shibboleth-hook/docroot/WEB-INF/liferay-plugin-package.properties
   <https://github.com/mhan810/liferay-plugins/pull/55/files#diff-22> (11)
   - *D* hooks/shibboleth-hook/docroot/WEB-INF/liferay-releng.properties
   <https://github.com/mhan810/liferay-plugins/pull/55/files#diff-23> (9)
   - *D* hooks/shibboleth-hook/docroot/WEB-INF/releng/icons/90x90.png
   <https://github.com/mhan810/liferay-plugins/pull/55/files#diff-24> (0)
   - *D* hooks/shibboleth-hook/docroot/WEB-INF/releng/screenshots/1.jpg
   <https://github.com/mhan810/liferay-plugins/pull/55/files#diff-25> (0)
   - *D* hooks/shibboleth-hook/docroot/WEB-INF/src/META-INF/javadocs-all.xml
   <https://github.com/mhan810/liferay-plugins/pull/55/files#diff-26> (106)
   - *D* hooks/shibboleth-hook/docroot/WEB-INF/src/META-INF/javadocs-rt.xml
   <https://github.com/mhan810/liferay-plugins/pull/55/files#diff-27> (2)
   - *D*
   hooks/shibboleth-hook/docroot/WEB-INF/src/com/liferay/shibboleth/hook/events/ShibbolethLogoutAction.java
   <https://github.com/mhan810/liferay-plugins/pull/55/files#diff-28> (72)
   - *D*
   hooks/shibboleth-hook/docroot/WEB-INF/src/com/liferay/shibboleth/hook/security/auth/ShibbolethAutoLogin.java
   <https://github.com/mhan810/liferay-plugins/pull/55/files#diff-29> (104)
   - *D*
   hooks/shibboleth-hook/docroot/WEB-INF/src/com/liferay/shibboleth/util/PropsKeys.java
   <https://github.com/mhan810/liferay-plugins/pull/55/files#diff-30> (33)
   - *D*
   hooks/shibboleth-hook/docroot/WEB-INF/src/com/liferay/shibboleth/util/PropsValues.java
   <https://github.com/mhan810/liferay-plugins/pull/55/files#diff-31> (38)
   - *D*
   hooks/shibboleth-hook/docroot/WEB-INF/src/com/liferay/shibboleth/util/ShibbolethUtil.java
   <https://github.com/mhan810/liferay-plugins/pull/55/files#diff-32> (36)
   - *D*
   hooks/shibboleth-hook/docroot/WEB-INF/src/content/Language.properties
   <https://github.com/mhan810/liferay-plugins/pull/55/files#diff-33> (3)
   - *D*
   hooks/shibboleth-hook/docroot/WEB-INF/src/content/Language_ar.properties
   <https://github.com/mhan810/liferay-plugins/pull/55/files#diff-34> (3)
   - *D*
   hooks/shibboleth-hook/docroot/WEB-INF/src/content/Language_bg.properties
   <https://github.com/mhan810/liferay-plugins/pull/55/files#diff-35> (3)
   - *D*
   hooks/shibboleth-hook/docroot/WEB-INF/src/content/Language_ca.properties
   <https://github.com/mhan810/liferay-plugins/pull/55/files#diff-36> (3)
   - *D*
   hooks/shibboleth-hook/docroot/WEB-INF/src/content/Language_cs.properties
   <https://github.com/mhan810/liferay-plugins/pull/55/files#diff-37> (3)
   - *D*
   hooks/shibboleth-hook/docroot/WEB-INF/src/content/Language_da.properties
   <https://github.com/mhan810/liferay-plugins/pull/55/files#diff-38> (3)
   - *D*
   hooks/shibboleth-hook/docroot/WEB-INF/src/content/Language_de.properties
   <https://github.com/mhan810/liferay-plugins/pull/55/files#diff-39> (3)
   - *D*
   hooks/shibboleth-hook/docroot/WEB-INF/src/content/Language_el.properties
   <https://github.com/mhan810/liferay-plugins/pull/55/files#diff-40> (3)
   - *D*
   hooks/shibboleth-hook/docroot/WEB-INF/src/content/Language_en.properties
   <https://github.com/mhan810/liferay-plugins/pull/55/files#diff-41> (3)
   - *D*
   hooks/shibboleth-hook/docroot/WEB-INF/src/content/Language_en_GB.properties
   <https://github.com/mhan810/liferay-plugins/pull/55/files#diff-42> (0)
   - *D*
   hooks/shibboleth-hook/docroot/WEB-INF/src/content/Language_es.properties
   <https://github.com/mhan810/liferay-plugins/pull/55/files#diff-43> (3)
   - *D*
   hooks/shibboleth-hook/docroot/WEB-INF/src/content/Language_et.properties
   <https://github.com/mhan810/liferay-plugins/pull/55/files#diff-44> (3)
   - *D*
   hooks/shibboleth-hook/docroot/WEB-INF/src/content/Language_eu.properties
   <https://github.com/mhan810/liferay-plugins/pull/55/files#diff-45> (3)
   - *D*
   hooks/shibboleth-hook/docroot/WEB-INF/src/content/Language_fa.properties
   <https://github.com/mhan810/liferay-plugins/pull/55/files#diff-46> (3)
   - *D*
   hooks/shibboleth-hook/docroot/WEB-INF/src/content/Language_fi.properties
   <https://github.com/mhan810/liferay-plugins/pull/55/files#diff-47> (3)
   - *D*
   hooks/shibboleth-hook/docroot/WEB-INF/src/content/Language_fr.properties
   <https://github.com/mhan810/liferay-plugins/pull/55/files#diff-48> (3)
   - *D*
   hooks/shibboleth-hook/docroot/WEB-INF/src/content/Language_fr_CA.properties
   <https://github.com/mhan810/liferay-plugins/pull/55/files#diff-49> (0)
   - *D*
   hooks/shibboleth-hook/docroot/WEB-INF/src/content/Language_gl.properties
   <https://github.com/mhan810/liferay-plugins/pull/55/files#diff-50> (3)
   - *D*
   hooks/shibboleth-hook/docroot/WEB-INF/src/content/Language_hi_IN.properties
   <https://github.com/mhan810/liferay-plugins/pull/55/files#diff-51> (3)
   - *D*
   hooks/shibboleth-hook/docroot/WEB-INF/src/content/Language_hr.properties
   <https://github.com/mhan810/liferay-plugins/pull/55/files#diff-52> (3)
   - *D*
   hooks/shibboleth-hook/docroot/WEB-INF/src/content/Language_hu.properties
   <https://github.com/mhan810/liferay-plugins/pull/55/files#diff-53> (3)
   - *D*
   hooks/shibboleth-hook/docroot/WEB-INF/src/content/Language_in.properties
   <https://github.com/mhan810/liferay-plugins/pull/55/files#diff-54> (3)
   - *D*
   hooks/shibboleth-hook/docroot/WEB-INF/src/content/Language_it.properties
   <https://github.com/mhan810/liferay-plugins/pull/55/files#diff-55> (3)
   - *D*
   hooks/shibboleth-hook/docroot/WEB-INF/src/content/Language_iw.properties
   <https://github.com/mhan810/liferay-plugins/pull/55/files#diff-56> (3)
   - *D*
   hooks/shibboleth-hook/docroot/WEB-INF/src/content/Language_ja.properties
   <https://github.com/mhan810/liferay-plugins/pull/55/files#diff-57> (3)
   - *D*
   hooks/shibboleth-hook/docroot/WEB-INF/src/content/Language_ko.properties
   <https://github.com/mhan810/liferay-plugins/pull/55/files#diff-58> (3)
   - *D*
   hooks/shibboleth-hook/docroot/WEB-INF/src/content/Language_lo.properties
   <https://github.com/mhan810/liferay-plugins/pull/55/files#diff-59> (3)
   - *D*
   hooks/shibboleth-hook/docroot/WEB-INF/src/content/Language_lt.properties
   <https://github.com/mhan810/liferay-plugins/pull/55/files#diff-60> (3)
   - *D*
   hooks/shibboleth-hook/docroot/WEB-INF/src/content/Language_nb.properties
   <https://github.com/mhan810/liferay-plugins/pull/55/files#diff-61> (3)
   - *D*
   hooks/shibboleth-hook/docroot/WEB-INF/src/content/Language_nl.properties
   <https://github.com/mhan810/liferay-plugins/pull/55/files#diff-62> (3)
   - *D*
   hooks/shibboleth-hook/docroot/WEB-INF/src/content/Language_nl_BE.properties
   <https://github.com/mhan810/liferay-plugins/pull/55/files#diff-63> (3)
   - *D*
   hooks/shibboleth-hook/docroot/WEB-INF/src/content/Language_pl.properties
   <https://github.com/mhan810/liferay-plugins/pull/55/files#diff-64> (3)
   - *D*
   hooks/shibboleth-hook/docroot/WEB-INF/src/content/Language_pt_BR.properties
   <https://github.com/mhan810/liferay-plugins/pull/55/files#diff-65> (3)
   - *D*
   hooks/shibboleth-hook/docroot/WEB-INF/src/content/Language_pt_PT.properties
   <https://github.com/mhan810/liferay-plugins/pull/55/files#diff-66> (3)
   - *D*
   hooks/shibboleth-hook/docroot/WEB-INF/src/content/Language_ro.properties
   <https://github.com/mhan810/liferay-plugins/pull/55/files#diff-67> (3)
   - *D*
   hooks/shibboleth-hook/docroot/WEB-INF/src/content/Language_ru.properties
   <https://github.com/mhan810/liferay-plugins/pull/55/files#diff-68> (3)
   - *D*
   hooks/shibboleth-hook/docroot/WEB-INF/src/content/Language_sk.properties
   <https://github.com/mhan810/liferay-plugins/pull/55/files#diff-69> (3)
   - *D*
   hooks/shibboleth-hook/docroot/WEB-INF/src/content/Language_sl.properties
   <https://github.com/mhan810/liferay-plugins/pull/55/files#diff-70> (3)
   - *D*
   hooks/shibboleth-hook/docroot/WEB-INF/src/content/Language_sr_RS.properties
   <https://github.com/mhan810/liferay-plugins/pull/55/files#diff-71> (3)
   - *D*
   hooks/shibboleth-hook/docroot/WEB-INF/src/content/Language_sr_RS_latin.properties
   <https://github.com/mhan810/liferay-plugins/pull/55/files#diff-72> (3)
   - *D*
   hooks/shibboleth-hook/docroot/WEB-INF/src/content/Language_sv.properties
   <https://github.com/mhan810/liferay-plugins/pull/55/files#diff-73> (3)
   - *D*
   hooks/shibboleth-hook/docroot/WEB-INF/src/content/Language_tr.properties
   <https://github.com/mhan810/liferay-plugins/pull/55/files#diff-74> (3)
   - *D*
   hooks/shibboleth-hook/docroot/WEB-INF/src/content/Language_uk.properties
   <https://github.com/mhan810/liferay-plugins/pull/55/files#diff-75> (3)
   - *D*
   hooks/shibboleth-hook/docroot/WEB-INF/src/content/Language_vi.properties
   <https://github.com/mhan810/liferay-plugins/pull/55/files#diff-76> (3)
   - *D*
   hooks/shibboleth-hook/docroot/WEB-INF/src/content/Language_zh_CN.properties
   <https://github.com/mhan810/liferay-plugins/pull/55/files#diff-77> (3)
   - *D*
   hooks/shibboleth-hook/docroot/WEB-INF/src/content/Language_zh_TW.properties
   <https://github.com/mhan810/liferay-plugins/pull/55/files#diff-78> (3)
   - *D* hooks/shibboleth-hook/docroot/WEB-INF/src/portal.properties
   <https://github.com/mhan810/liferay-plugins/pull/55/files#diff-79> (32)
   - *M* layouttpl/build.xml
   <https://github.com/mhan810/liferay-plugins/pull/55/files#diff-80> (67)
   - *M* layouttpl/create.bat
   <https://github.com/mhan810/liferay-plugins/pull/55/files#diff-81> (2)
   - *M* layouttpl/create.sh
   <https://github.com/mhan810/liferay-plugins/pull/55/files#diff-82> (2)
   - *M* portlets/build.xml
   <https://github.com/mhan810/liferay-plugins/pull/55/files#diff-83> (285)
   - *M* portlets/create.bat
   <https://github.com/mhan810/liferay-plugins/pull/55/files#diff-84> (2)
   - *M* portlets/create.sh
   <https://github.com/mhan810/liferay-plugins/pull/55/files#diff-85> (4)
   - *M* portlets/test-cache-configuration-portlet/docroot/init.jsp
   <https://github.com/mhan810/liferay-plugins/pull/55/files#diff-86> (4)
   - *M* portlets/test-cache-configuration-portlet/docroot/view.jsp
   <https://github.com/mhan810/liferay-plugins/pull/55/files#diff-87> (4)
   - *M* sdk.gradle
   <https://github.com/mhan810/liferay-plugins/pull/55/files#diff-88> (415)
   - *M*
   shared/alloy-mvc-shared/src/com/liferay/alloy/mvc/BaseAlloyControllerImpl.java
   <https://github.com/mhan810/liferay-plugins/pull/55/files#diff-89> (41)
   - *M*
   shared/solr4-shared/src/com/liferay/portal/search/solr/SolrIndexSearcher.java
   <https://github.com/mhan810/liferay-plugins/pull/55/files#diff-90> (16)
   - *M* themes/build.xml
   <https://github.com/mhan810/liferay-plugins/pull/55/files#diff-91> (47)
   - *M* themes/create.bat
   <https://github.com/mhan810/liferay-plugins/pull/55/files#diff-92> (2)
   - *M* themes/create.sh
   <https://github.com/mhan810/liferay-plugins/pull/55/files#diff-93> (2)
   - *M* tools/templates/hook_tmpl/ivy.xml
   <https://github.com/mhan810/liferay-plugins/pull/55/files#diff-94> (2)
   - *M* util.gradle
   <https://github.com/mhan810/liferay-plugins/pull/55/files#diff-95> (9)
   - *M* versions.gradle
   <https://github.com/mhan810/liferay-plugins/pull/55/files#diff-96> (2)
   - *M* webs/build.xml
   <https://github.com/mhan810/liferay-plugins/pull/55/files#diff-97> (41)
   - *M* webs/create.bat
   <https://github.com/mhan810/liferay-plugins/pull/55/files#diff-98> (2)
   - *M* webs/create.sh
   <https://github.com/mhan810/liferay-plugins/pull/55/files#diff-99> (4)
   - *M* webs/solr4-web/docroot/WEB-INF/conf/schema.xml
   <https://github.com/mhan810/liferay-plugins/pull/55/files#diff-100> (2)
   - *M*
   webs/sync-web/docroot/WEB-INF/src/com/liferay/sync/servlet/DownloadServlet.java
   <https://github.com/mhan810/liferay-plugins/pull/55/files#diff-101> (8)

Patch Links:

   - https://github.com/mhan810/liferay-plugins/pull/55.patch
   - https://github.com/mhan810/liferay-plugins/pull/55.diff

--
Reply to this email directly or view it on GitHub
<https://github.com/mhan810/liferay-plugins/pull/55>.

**Comment by mhan810** [comment]
@arboliviera can you look @ this one?

**Comment by mhan810** [comment]
@aboliviera

**Comment by jcampoy** [comment]
Perfect! Thanks!

**Pull request closed without merging**
